{
  "$schema": "https://raw.githubusercontent.com/railwayapp/nixpacks/main/nixpacks.schema.json",
  "phases": {
    "setup": {
      "nixPkgs": ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.pdo_mysql"]
    }
  }
}
